# ==============================================================================
# Terrazzo Dark
# ==============================================================================

background #2f3238
foreground #cfd3d8

selection_background #4a5058
selection_foreground #cfd3d8

cursor #78a4c4
cursor_text_color #2f3238

url_color #78a4c4
active_border_color #78a4c4
inactive_border_color #535861
bell_border_color #c9ad79

tab_bar_background #383B42
active_tab_foreground #cfd3d8
active_tab_background #2f3238
inactive_tab_foreground #aeb5bd
inactive_tab_background #383B42

# ANSI

color0  #41454D
color1  #c97a80
color2  #8eae7a
color3  #c9ad79
color4  #78a4c4
color5  #a98abf
color6  #68b0a6
color7  #aeb5bd

color8  #8d949c
color9  #c97a80
color10 #8eae7a
color11 #b0b65c
color12 #6499cc
color13 #c27aa8
color14 #68b0a6
color15 #cfd3d8
