# ==============================================================================
# Terrazzo Light
# ==============================================================================

background #F2F1EE
foreground #4A4C52

selection_background #DCD8D2
selection_foreground #4A4C52

cursor #5B8FA8
cursor_text_color #F2F1EE

url_color #5B8FA8
active_border_color #5B8FA8
inactive_border_color #D3D0CA
bell_border_color #B08B4F

tab_bar_background #EAE8E4
active_tab_foreground #4A4C52
active_tab_background #F2F1EE
inactive_tab_foreground #6B6E73
inactive_tab_background #EAE8E4

# ANSI

color0  #E5E3DF
color1  #C96A61
color2  #6E9B73
color3  #B08B4F
color4  #5B8FA8
color5  #9A6F96
color6  #4A9690
color7  #6B6E73

color8  #8F918F
color9  #AF5C54
color10 #608764
color11 #8C9236
color12 #3F7CA3
color13 #C0658A
color14 #40827D
color15 #4A4C52
